package forme.polisa;

import domen.CenovnikOsiguranja;
import domen.StavkaPolise;
import java.io.IOException;
import java.util.List;
import javax.swing.SwingUtilities;
import static jdk.nashorn.internal.objects.NativeMath.round;
import komunikacija.Komunikacija;
import transfer.Operacija;
import transfer.TransferObjekatOdgovor;
import transfer.TransferObjekatZahtev;
import util.Sesija;

/**
 *
 * @author Darko
 */
public class FrmObavezno extends javax.swing.JDialog {

    TransferObjekatZahtev toZahtev;
    TransferObjekatOdgovor toOdgovor;
    FrmPolisa forma = null;
    StavkaPolise sp = new StavkaPolise();

    /**
     * Creates new form FrmObavezno
     *
     * @param parent
     * @param modal
     */
    public FrmObavezno(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKategorija = new javax.swing.JLabel();
        cmbKategorija = new javax.swing.JComboBox();
        lblPremijskiStepen = new javax.swing.JLabel();
        cmbPremijskiStepen = new javax.swing.JComboBox();
        btnOdustani = new javax.swing.JButton();
        chbTaxi = new javax.swing.JCheckBox();
        chbRentACar = new javax.swing.JCheckBox();
        chbInvalid = new javax.swing.JCheckBox();
        btnUbaci = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblKategorija.setText("Kategorija: ");

        cmbKategorija.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblPremijskiStepen.setText("Premijski stepen: ");

        cmbPremijskiStepen.setMaximumRowCount(12);
        cmbPremijskiStepen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cmbPremijskiStepen.setSelectedIndex(3);

        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        chbTaxi.setText("Taxi vozilo");

        chbRentACar.setText("Rent-a-car");

        chbInvalid.setText("Prilagodjeno vozilo");

        btnUbaci.setText("Ubaci");
        btnUbaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbaciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKategorija)
                            .addComponent(lblPremijskiStepen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbKategorija, 0, 199, Short.MAX_VALUE)
                            .addComponent(cmbPremijskiStepen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 177, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btnUbaci, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnOdustani))
                            .addComponent(chbInvalid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chbTaxi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chbRentACar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKategorija)
                    .addComponent(cmbKategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPremijskiStepen)
                    .addComponent(cmbPremijskiStepen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(chbTaxi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbRentACar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbInvalid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOdustani)
                    .addComponent(btnUbaci))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUbaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbaciActionPerformed
        CenovnikOsiguranja cenovnik = (CenovnikOsiguranja) cmbKategorija.getSelectedItem();
        int i = Integer.parseInt((String) cmbPremijskiStepen.getSelectedItem());
        String naziv = Sesija.getInstance().get("obavezno").toString();
        double taxi = (chbTaxi.isSelected()) ? 1.20 : 1.00;
        double rent = (chbTaxi.isSelected()) ? 1.40 : 1.00;
        double invalid = (chbTaxi.isSelected()) ? 0.90 : 1.00;
        if (forma == null) {
            System.out.println("Doslo je do greske.");
        }
        double cena = cenovnik.getCena() * sp.getKoeficijent(i) * taxi * rent * invalid;

        forma.dodajStavku(new StavkaPolise(-1, naziv, cena, cenovnik), i);

        Sesija.getInstance().remove("obavezno");
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_btnUbaciActionPerformed

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_btnOdustaniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmObavezno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmObavezno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmObavezno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmObavezno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmObavezno dialog = new FrmObavezno(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdustani;
    public javax.swing.JButton btnUbaci;
    private javax.swing.JCheckBox chbInvalid;
    private javax.swing.JCheckBox chbRentACar;
    private javax.swing.JCheckBox chbTaxi;
    private javax.swing.JComboBox cmbKategorija;
    private javax.swing.JComboBox cmbPremijskiStepen;
    private javax.swing.JLabel lblKategorija;
    private javax.swing.JLabel lblPremijskiStepen;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        toZahtev = new TransferObjekatZahtev();
        toZahtev.setOperacija(Operacija.VRATI_CENOVNIK);
        try {
            Komunikacija.getInstance().posalji(toZahtev);
            toOdgovor = Komunikacija.getInstance().procitaj();
        } catch (IOException | ClassNotFoundException ex) {
            System.out.println("Greska: " + ex);
        }
        List<CenovnikOsiguranja> listaC = (List<CenovnikOsiguranja>) toOdgovor.getRezultat();
        cmbKategorija.removeAllItems();
        for (CenovnikOsiguranja cenovnik : listaC) {
            cmbKategorija.addItem(cenovnik);
        }
    }

    public void setForma(FrmPolisa aThis) {
        forma = aThis;
    }
}
