package forme.polisa;

import domen.Klijent;
import domen.Polisa;
import domen.Referent;
import domen.StavkaPolise;
import domen.TipOsiguranja;
import domen.Vozilo;
import forme.polisa.model.ModelTabeleStavkaPolise;
import java.awt.Frame;
import java.awt.Window;
import java.io.IOException;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import kontroler.Kontroler;
import transfer.TransferObjekatOdgovor;
import util.Sesija;

/**
 *
 * @author Darko
 */
public class FrmPolisa extends javax.swing.JPanel {

    TransferObjekatOdgovor toOdgovor;
    int premijskiStepen = -1;

    /**
     * Creates new form FrmPolisa
     */
    public FrmPolisa() {
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblStavke = new javax.swing.JTable();
        btnSacuvaj = new javax.swing.JButton();
        btnOdustani = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbKlijent = new javax.swing.JComboBox();
        cmbVozilo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cmbTipOsiguranja = new javax.swing.JComboBox();
        btnDodaj = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();

        jtblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblStavke);

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnOdustani.setText("Odustani");
        btnOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniActionPerformed(evt);
            }
        });

        jLabel1.setText("Klijent: ");

        jLabel2.setText("Vozilo: ");

        cmbKlijent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbVozilo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Tip osiguranja: ");

        cmbTipOsiguranja.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnDodaj.setText("Dodaj stavku");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi stavku");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnSacuvaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOdustani))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbVozilo, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDodaj)
                                .addGap(71, 71, 71)
                                .addComponent(btnObrisi))
                            .addComponent(cmbTipOsiguranja, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cmbVozilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cmbTipOsiguranja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnObrisi)
                    .addComponent(btnDodaj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvaj)
                    .addComponent(btnOdustani))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        TipOsiguranja to = (TipOsiguranja) cmbTipOsiguranja.getSelectedItem();
        switch (to) {
            case OBAVEZNO:
                Sesija.getInstance().put("obavezno", to);
                // JDialog Auto-odgovornost
                FrmObavezno obavezno = new FrmObavezno(getParentFrame(), true);
                obavezno.setForma(this);
                obavezno.setVisible(true);
                break;
            case KASKO:
                Sesija.getInstance().put("kasko", to);
                // JDialog Kasko
                FrmKasko kasko = new FrmKasko(getParentFrame(), true);
                kasko.setForma(this);
                kasko.setVisible(true);
                break;
            case MINI_KASKO:
                Sesija.getInstance().put("kasko", to);
                // JDialog Mini-kasko
                FrmKasko miniKasko = new FrmKasko(getParentFrame(), true);
                miniKasko.setForma(this);
                miniKasko.setVisible(true);
                break;
            case ZELENA_KARTA:
                dodajStavku(new StavkaPolise(-1, -1, to.toString(), 2500.00, null), -1);
                break;
            case AUTO_NEZGODA:
                dodajStavku(new StavkaPolise(-1, -1, to.toString(), 9800.00, null), -1);
                break;
            case POMOC_NA_PUTU:
                dodajStavku(new StavkaPolise(-1, -1, to.toString(), 2500.00, null), -1);
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        ModelTabeleStavkaPolise mtsp = (ModelTabeleStavkaPolise) jtblStavke.getModel();
        if (mtsp.getRowCount() <= 0) {
            JOptionPane.showMessageDialog(this, "Potrebno je da unesete minimum jednu stavku!");
            return;
        }

        Klijent k = (Klijent) cmbKlijent.getSelectedItem();
        Vozilo v = (Vozilo) cmbVozilo.getSelectedItem();
        Polisa p = mtsp.getPolisa();
        p.setPolisaId(-1);
        p.setKlijent(k);
        p.setVozilo(v);
        p.setReferentUgovaranje((Referent) Sesija.getInstance().get("Referent"));
        p.setReferentRaskidanje(null);
        p.setDatumUgovaranja(new Date());
        p.setDatumRaskidanja(null);

        try {
            toOdgovor = Kontroler.getInstance().zapamtiPolisu(p);
        } catch (Exception e) {
            System.out.println("Greska: " + e);
        }
        if (toOdgovor.getIzuzetak() != null) {
            JOptionPane.showMessageDialog(this, toOdgovor.getIzuzetak());
            return;
        }
        JOptionPane.showMessageDialog(this, toOdgovor.getPoruka());
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniActionPerformed
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_btnOdustaniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        int index = jtblStavke.getSelectedRow();
        if (index != -1) {
            ModelTabeleStavkaPolise model = (ModelTabeleStavkaPolise) jtblStavke.getModel();
            model.obrisiStavku(index);
        } else {
            JOptionPane.showMessageDialog(this, "Odaberite stavku koju zelite da obrisete!");
        }
    }//GEN-LAST:event_btnObrisiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnOdustani;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbKlijent;
    private javax.swing.JComboBox cmbTipOsiguranja;
    private javax.swing.JComboBox cmbVozilo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblStavke;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        ModelTabeleStavkaPolise mtsp = new ModelTabeleStavkaPolise(new Polisa());
        jtblStavke.setModel(mtsp);

        try {
            List<Klijent> listaK = Kontroler.getInstance().vratiKlijente();
            List<Vozilo> listaV = Kontroler.getInstance().vratiVozila();

            cmbKlijent.removeAllItems();
            for (Klijent klijent : listaK) {
                cmbKlijent.addItem(klijent);
            }
            cmbVozilo.removeAllItems();
            for (Vozilo vozilo : listaV) {
                cmbVozilo.addItem(vozilo);
            }
        } catch (IOException | ClassNotFoundException e) {
            System.out.println("Greska: " + e);
        }

        cmbTipOsiguranja.setModel(new DefaultComboBoxModel<>(TipOsiguranja.values()));
    }

    public void dodajStavku(StavkaPolise sp, int stepen) {
        ModelTabeleStavkaPolise mtsp = (ModelTabeleStavkaPolise) jtblStavke.getModel();
        if (stepen > 0) {
            premijskiStepen = stepen;
            mtsp.getPolisa().setPremijskiStepen(stepen);
        }
        mtsp.dodajStavku(sp);
    }

    private Frame getParentFrame() {
        Window parentWindow = SwingUtilities.windowForComponent(this);
        Frame parentFrame = null;
        if (parentWindow instanceof Frame) {
            parentFrame = (Frame) parentWindow;
        }
        return parentFrame;
    }
}
